import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import  styles from "./layout.module.css";
import {Providers} from "@/app/providers";

//コンポーネント
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <Providers>
      {/* コンポーネント部分 */}
        <div className={styles.layoutWrapper}>
          <Header />
          <main className={styles.mainContent}>{children}</main>
        </div>
        <Footer />
      </Providers>
      </body>
    </html>
  );
}
