import type { Metadata } from "next";
import "../styles/globals.css";
import  styles from "../styles/layout.module.css";
import {Providers} from "@/app/Providers";

//コンポーネント
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";

// googlefonts
import { Noto_Sans_JP, Alice } from 'next/font/google'

const notoSansJP = Noto_Sans_JP({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
})

const alice = Alice({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Chordia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${alice.className} ${notoSansJP.className}`}>
      <Providers>
      {/* コンポーネント部分 */}
        <div className={styles.layoutWrapper}>
          <Header />
          <main className={styles.mainContent}>{children}</main>
        </div>
        <Footer />
      </Providers>
      </body>
    </html>
  );
}
